apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: aws-iam-role-maker
build:
  artifacts:
  - image: iam-role-maker
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
